routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KendaraanController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\DataBBMController;
use App\Http\Controllers\PemakaianController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('admin.layout');
// });

// Route::get('/home', [HomeController::class, 'index']);

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    
});

Route::get('/home', [HomeController::class, 'index']);
Route::resource('kendaraan', KendaraanController::class);
Route::resource('service', ServiceController::class);
Route::resource('bbm', DataBBMController::class);
Route::resource('pemakaian', PemakaianController::class);
Route::resource('users', UserController::class);

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    use HasFactory;
    protected $fillable = [
        'id',
        'kendaraan_id',
        'tanggal',
        'penanggung_jawab',
        'jenis_service',
        'biaya',
        'nota'
    ];
    protected $primaryKey='id';
    protected $table = 'data_service';
    public function serviceKendaraan()
    {
        return $this->belongsTo(Kendaraan::class, 'kendaraan_id');
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Service;
use Illuminate\Support\Facades\Storage;
use App\Models\Kendaraan;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $kendaraan = Kendaraan::all();
        $service = Service::with('serviceKendaraan')->get();
        return view('service.index', compact('service', 'kendaraan'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'penanggung_jawab' => 'required',
            'tanggal' => 'required',
            'jenis_service' => 'required',
            'biaya' => 'required',
            'nota' => 'required|mimes: jpg,jpeg,png'
        ]);

        $file_name = $request->file('nota')->getClientOriginalName();
       $request->file('nota')->move('upload/', $file_name);

        Service::create([
            'kendaraan_id' => $request->kendaraan_id,
            'tanggal' => $request->tanggal,
            'penanggung_jawab' => $request->penanggung_jawab,
            'jenis_service' => $request->jenis_service,
            'biaya' => $request->biaya,
            'nota' => $file_name,
        ]);
        return redirect()->route('service.index')->with('success', 'Data Berhasil Disimpan!');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'penanggung_jawab' => 'required',
            'tanggal' => 'required',
            'jenis_service' => 'required',
            'biaya' => 'required',
            'nota' => 'required||mimes: jpg,jpeg,png'
        ]);

        if (empty($request->file('nota'))) {
            $data = Service::find($id);
            $data->update([
                'kendaraan_id' => $request->kendaraan_id,
                'tanggal' => $request->tanggal,
                'penanggung_jawab' => $request->penanggung_jawab,
                'jenis_service' => $request->jenis_service,
                'biaya' => $request->biaya,
            ]);
            return redirect()->route('service.index')->with('success', 'Data Berhasil Diubah!');
        } else {
            $data = Service::find($id);
            Storage::delete($data->nota);
            $file_name = $request->file('nota')->getClientOriginalName();
            $request->file('nota')->move('upload/', $file_name);
            $data->update([
                'kendaraan_id' => $request->kendaraan_id,
                'tanggal' => $request->tanggal,
                'penanggung_jawab' => $request->penanggung_jawab,
                'jenis_service' => $request->jenis_service,
                'biaya' => $request->biaya,
                'nota' => $file_name
            ]);
            return redirect()->route('service.index')->with('success', 'Data Berhasil Diubah!');
        }
        
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $service = Service::find($id);
        $service->delete();

        return redirect()->route('service.index')->with('success', 'Data Berhasil Dihapus!');
    }
}

resources/views/service/edit.blade.php
@foreach ($service as $item)
<div class="modal fade" id="editModal{{$item->id}}" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{ route('service.update', $item->id)}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
        <div class="modal-body">
            <div class="form-group">
                <label for="exampleFormControlSelect1">Tipe Kendaraan</label>
                <select class="form-control" name="kendaraan_id">
                    <option value="{{$item->kendaraan_id}}" selected>{{$item->serviceKendaraan->merek_tipe}}&nbsp;-&nbsp;{{$item->serviceKendaraan->plat_nomor}}</option>
                  @foreach ($kendaraan as $data)
                  <option value="{{$data->id}}">{{$data->merek_tipe}}&nbsp;-&nbsp;{{$data->plat_nomor}}</option> 
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Tanggal</label>
                <input type="date" class="form-control" name="tanggal" value="{{$item->tanggal}}" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Penanggungjawab</label>
                <input type="text" class="form-control" name="penanggung_jawab" value="{{$item->penanggung_jawab}}" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Jenis Service</label>
                <input type="text" class="form-control" name="jenis_service" value="{{$item->jenis_service}}" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Biaya</label>
                <input type="text" class="form-control" name="biaya" value="{{$item->biaya}}" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Nota</label>
                <input type="file" class="form-control" name="nota" value="{{$item->nota}}" required>
                <img src="{{asset('upload/'.$item->nota) }}" width="120px">
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
    </form>
      </div>
    </div>
  </div>
  @endforeach

resources/views/service/index.blade.php
@extends('admin.layout')
@section('css')
<link href="{{asset('template/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endsection

@section('content')
    
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Data Service</h1>
    </div>

   

         <!-- DataTales Example -->
         <div class="card shadow mb-4">
             <div class="card-header py-3">
                 <h6 class="m-0 font-weight-bold text-primary">DataTables
                 <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#exampleModal">
                    + Data Service
                  </button>
                </h6>
             </div>
             <div class="card-body">
                 <div class="table-responsive">
                     <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                         <thead>
                             <tr>
                                 <th>Merk/Tipe</th>
                                 <th>Plat Nomor</th>
                                 <th>Tanggal</th>
                                 <th>Penanggung Jawab</th>
                                 <th>Jenis Service</th>
                                 <th>Biaya</th>
                                 <th>Nota</th>
                                 <th>Action</th>
                            </tr>
                         </thead>
                         <tbody>
                            @foreach ($service as $item)
                                <tr>
                                    <td>{{$item->serviceKendaraan->merek_tipe}}</td>
                                    <td>{{$item->serviceKendaraan->plat_nomor}}</td>
                                    <td>{{$item->tanggal}}</td>
                                    <td>{{$item->penanggung_jawab}}</td>
                                    <td>{{$item->jenis_service}}</td>
                                    <td>{{$item->biaya}}</td>
                                    <td>
                                        <img src="{{asset('upload/'.$item->nota) }}" width="120px">
                                    </td>
                                    <td class="text-center" >
                                        <a href="#" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#editModal{{$item->id}}">edit</a>
                                        <form class="d-inline" method="POST" action="{{ route('service.destroy', $item->id) }}">
                                            @csrf
                                            @method('Delete')
                                            <button type="submit" class="btn btn-danger btn-sm">hapus</button>
                                        </form>
                                       
                                    </td>
                                </tr>
                            @endforeach
                         </tbody>
                     </table>
                
             </div>
         </div>
    </div>

</div>


  
  <!-- Modal Add -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{ route('service.store')}}" method="POST" enctype="multipart/form-data">
            @csrf
        <div class="modal-body">
            <div class="form-group">
                <label for="exampleFormControlSelect1">Merek Kendaraan</label>
                <select class="form-control" name="kendaraan_id">
                    <option selected>Pilih Kendaraan</option>
                  @foreach ($kendaraan as $item)
                  <option value="{{$item->id}}">{{$item->merek_tipe}}&nbsp;-&nbsp;{{$item->plat_nomor}}</option> 
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Tanggal</label>
                <input type="date" class="form-control" name="tanggal" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Penanggungjawab</label>
                <input type="text" class="form-control" name="penanggung_jawab" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Jenis Service</label>
                <input type="text" class="form-control" name="jenis_service" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Biaya</label>
                <input type="text" class="form-control" name="biaya" required>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Nota</label>
                <input type="file" class="form-control" name="nota" required>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
    </form>
      </div>
    </div>
  </div>

@include('sweetalert::alert')
@include('service.edit')
@endsection

@section('script')
<script src="{{asset('template/vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('template/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('template/js/demo/datatables-demo.js')}}"></script>


@endsection