routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KendaraanController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\DataBBMController;
use App\Http\Controllers\PemakaianController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('admin.layout');
// });

// Route::get('/home', [HomeController::class, 'index']);

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    
});

Route::get('/home', [HomeController::class, 'index']);
Route::resource('kendaraan', KendaraanController::class);
Route::resource('service', ServiceController::class);
Route::resource('bbm', DataBBMController::class);
Route::resource('pemakaian', PemakaianController::class);
Route::resource('users', UserController::class);

app/Models/Kendaraan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kendaraan extends Model
{
    use HasFactory;
    protected $fillable = [
        'id',
        'merek_tipe',
        'plat_nomor',
        'kategori'
    ];
    protected $primaryKey='id';
    protected $table = 'kendaraan';
    public function serviceKendaraan()
    {
        return $this->belongsTo(Service::class);
    }
    public function bbmKendaraan()
    {
        return $this->belongsTo(DataBBM::class);
    }
    public function pemakaian()
    {
        return $this->belongsTo(Pemakaian::class);
    }
}

app/Http/Controllers/KendaraanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kendaraan;

class KendaraanController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $kendaraan = Kendaraan::all();
        return view('kendaraan.index', compact('kendaraan'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        
        $request->validate([
            'merek_tipe' => 'required',
            'plat_nomor' => 'required',
        ]);
        Kendaraan::create([
            'merek_tipe' => $request->merek_tipe,
            'plat_nomor' => $request->plat_nomor,
            'kategori' => $request->kategori,
        ]);
        return redirect()->route('kendaraan.index')->with('success', 'Data Berhasil Disimpan!');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        
        
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $request->validate([
            'merek_tipe' => 'required',
            'plat_nomor' => 'required',
        ]);
        $kendaraan = Kendaraan::find($id);
        $kendaraan->update([
            'merek_tipe' => $request->merek_tipe,
            'plat_nomor' => $request->plat_nomor,
            'kategori' => $request->kategori,
        ]);
        return redirect()->route('kendaraan.index')->with('success', 'Data Berhasil Diupdate!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $kendaraan = Kendaraan::find($id);
        $kendaraan->delete();

        return redirect()->route('kendaraan.index')->with('success', 'Data Berhasil Dihapus!');
        
    
    }
}

resources/views/kendaraan/edit.blade.php
@foreach ($kendaraan as $item)
<div class="modal fade" id="editModal{{$item->id}}" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{ route('kendaraan.update', $item->id)}}" method="POST">
            @csrf
            @method('PUT')
        <div class="modal-body">
            <div class="form-group">
                <label for="exampleInputPassword1">Merek/Tipe Kendaraan</label>
                <input type="text" class="form-control" name="merek_tipe" value="{{$item->merek_tipe}}">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Plat Nomor</label>
                <input type="text" class="form-control" name="plat_nomor" value="{{$item->plat_nomor}}">
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Kategori Kendaraan</label>
                <select class="form-control" name="kategori">
                  <option value="Motor" {{ ("Motor" == $item->kategori) ? 'selected' : '' }}>Motor</option>
                  <option value="Mobil" {{ ("Mobil" == $item->kategori) ? 'selected' : '' }}>Mobil</option>
                  <option value="Alat Berat" {{ ("Alat Berat" == $item->kategori) ? 'selected' : '' }}>Alat Berat</option>
                  <option value="Mobil Angkutan Barang" {{ ("Mobil Angkutan Barang" == $item->kategori) ? 'selected' : '' }}>Mobil Angkutan Barang</option>
                </select>
              </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
    </form>
      </div>
    </div>
  </div>
  @endforeach

resources/views/kendaraan/index.blade.php
@extends('admin.layout')
@section('css')
<link href="{{asset('template/vendor/datatables/dataTables.bootstrap4.min.css')}}" rel="stylesheet">
@endsection

@section('content')
    
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Data Kendaraan</h1>
    </div>

   

         <!-- DataTales Example -->
         <div class="card shadow mb-4">
             <div class="card-header py-3">
                 <h6 class="m-0 font-weight-bold text-primary">DataTables
                 <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#exampleModal">
                    + Data Kendaraan
                  </button>
                </h6>
             </div>
             <div class="card-body">
                 <div class="table-responsive">
                     <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                         <thead>
                             <tr>
                                 <th>Merk/Tipe</th>
                                 <th>Plat Nomor</th>
                                 <th>Kategori</th>
                                 <th>Action</th>
                            </tr>
                         </thead>
                         <tbody>
                            @foreach ($kendaraan as $item)
                                <tr>
                                    <td>{{$item->merek_tipe}}</td>
                                    <td>{{$item->plat_nomor}}</td>
                                    <td>{{$item->kategori}}</td>
                                    <td class="text-center" >
                                        <a href="#" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#editModal{{$item->id}}">edit</a>
                                        <form class="d-inline" method="POST" action="{{ route('kendaraan.destroy', $item->id) }}">
                                            @csrf
                                            @method('Delete')
                                            <button type="submit" class="btn btn-danger btn-sm">hapus</button>
                                        </form>
                                       
                                    </td>
                                </tr>
                            @endforeach
                         </tbody>
                     </table>
                
             </div>
         </div>
    </div>

</div>


  
  <!-- Modal Add -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{{ route('kendaraan.store')}}" method="POST">
            @csrf
        <div class="modal-body">
            <div class="form-group">
                <label for="exampleInputPassword1">Merek/Tipe Kendaraan</label>
                <input type="text" class="form-control" name="merek_tipe">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Plat Nomor</label>
                <input type="text" class="form-control" name="plat_nomor">
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Kategori Kendaraan</label>
                <select class="form-control" name="kategori">
                    <option selected>Pilih Kategori Kendaran</option>
                  <option value="Motor">Motor</option>
                  <option value="Mobil">Mobil</option>
                  <option value="Alat Berat">Alat Berat</option>
                  <option value="Angkutan Barang">Angkutan Barang</option>
                </select>
              </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
    </form>
      </div>
    </div>
  </div>

@include('sweetalert::alert')
@include('kendaraan.edit')
@endsection

@section('script')
<script src="{{asset('template/vendor/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('template/vendor/datatables/dataTables.bootstrap4.min.js')}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('template/js/demo/datatables-demo.js')}}"></script>


@endsection